appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: XqLE+iDoPm16DNKl6jBScVTkVOaeGz9FxpulyDcy7Xk6A3c5qecYL6pos2QPcjR1y4UYdhihNXqo/yKbhqhmTjZiH5Oevyma1D8A1crC0BGISjZksa1m8F6un6LHWLwG7/uYmps+p1Rb3CYZgEJUM9OQkhgwvliY9sWKu7Mrwm1HlxKDzWUyNBzGXTFgjeloRavS+TGhkzNQCl1IIuyiiD0l/UL7qi6FG3fXvF6EdTuWiLPoWdfU3NqBV0q0rofA7sf9JsHrQOalKAlgECxhmZqrJrlXDXruz/pKo0zRRhbP6lvnaECS4iZTGdJOB27lU66PHqd/Py5bAtJHHSa0U0iz0/TPNBVca/qyx1+5ClhrciogrUdItFtff3T20RKSDR/yqzOCWJG0Q4Y+Ff5BYMhwarWgTYQPVEkemmntTgpcMBC8gjBZ3h8GJ4Vfemwuh+h3kTU2wZi3x9canabJY/ALNp8fc3c2Aq8/Fe4NaufNnS0q3Hi5goGtq/lN2hOOgFqYhqw9kuU4aBi7kG77NAWRa9eGVsLqLZ6MhJLlGnqrrr3J4k2USGc+SthB7hYMmnPK46+2u37eAwPVSAmGJnHRikjkoYKiEHG6uHaoS+KYHvDXw1/6pem7JUHeNi/ZLzlLo6udqYRNzmGrHwqTWrPtdED8hUPLqAcnpXzhbx8=}
provider:
  win: azure
conda_forge_output_validation: true
